/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shayantan_tech;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author shaya
 */
public class AdminUI extends javax.swing.JFrame {
    String filename=null;
    byte[] person_image=null;

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
       // String name;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        room = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        alexa = new javax.swing.JCheckBox();
        google = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sugprod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sugprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 16, 191, 33));

        jLabel3.setText("price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 86, 234, 33));

        jLabel4.setText("Brand");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 234, 33));

        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 234, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 86, 215, 33));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 21, 215, 33));
        getContentPane().add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 215, 33));
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 215, 33));

        room.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bedroom", "Kitchen", "Living Room", " " }));
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 215, 36));

        jLabel6.setText("Room Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 234, 36));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/iconfinder_Add button_40098.png"))); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 141, 78));

        alexa.setText("Alexa");
        alexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alexaActionPerformed(evt);
            }
        });
        getContentPane().add(alexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        google.setText("Google");
        getContentPane().add(google, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel7.setText("Compatibility");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel1.setText("Suggested categories");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 197, -1));
        getContentPane().add(sugprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 201, -1));

        jLabel8.setText("price of suggested product");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 234, -1));
        getContentPane().add(sugprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 201, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/iconfinder_log-out_2914472.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 150, 78));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 61, 215, 16));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 215, 16));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\shaya\\Downloads\\iconfinder_Safe_877017.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 580, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(sugprod.getText().trim().isEmpty())
        {
            if(name.getText().trim().isEmpty() && price.getText().trim().isEmpty())
            {
                jLabel9.setText("Cannot be Empty");
                jLabel10.setText("Cannot be Empty");
            }
            else if(name.getText().trim().isEmpty())
            {
                jLabel9.setText("Cannot be Empty");
            }
            else if(price.getText().trim().isEmpty())
            {
                jLabel10.setText("Cannot be Empty");
            }
            else
            {
            try
        {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
             Connection con = DriverManager.getConnection(url);
             String query = "Insert into product2(name,price,brand,category,room,alexa,google)values(?,?,?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, name.getText());
            // System.out.println(name.getText());
             pst.setString(2, price.getText());
             pst.setString(3, brand.getText());
             pst.setString(4, category.getText());
             String roomtype;
             roomtype=room.getSelectedItem().toString();
             pst.setString(5, roomtype);
            // pst.setBytes(6, lbl_img.getBytes);
             String assistant="";
             if(alexa.isSelected())
             {
                 assistant="true";
             }
             
             pst.setString(6, assistant);
             String assistant1="";
             if(google.isSelected())
             {
                 assistant1="true";
             }
             pst.setString(7, assistant1);
             //pst.setString(8,sugprod.getText());
             //pst.setString(9,sugprice.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"Success");
             name.setText("");
             price.setText("");
             brand.setText("");
             category.setText("");
             sugprod.setText("");
             sugprice.setText("");
             google.setSelected(false);
             alexa.setSelected(false);
            /* String image=jTextField1.getText();
             image = image.replace("\\","\\\\");
                     
             
          //   pst.setString(1, name.getText());*/
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
            }
        
        }
        else
        {
        try
        {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
             Connection con = DriverManager.getConnection(url);
             String query = "Insert into product2(name,price,brand,category,room,alexa,google,sugprod,sugprodprice)values(?,?,?,?,?,?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, name.getText());
            // System.out.println(name.getText());
             pst.setString(2, price.getText());
             pst.setString(3, brand.getText());
             pst.setString(4, category.getText());
             String roomtype;
             roomtype=room.getSelectedItem().toString();
             pst.setString(5, roomtype);
            // pst.setBytes(6, lbl_img.getBytes);
             String assistant="";
             if(alexa.isSelected())
             {
                 assistant="true";
             }
             
             pst.setString(6, assistant);
             String assistant1="";
             if(google.isSelected())
             {
                 assistant1="true";
             }
             pst.setString(7, assistant1);
             pst.setString(8,sugprod.getText());
             pst.setString(9,sugprice.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"Success");
             name.setText("");
             price.setText("");
             brand.setText("");
             category.setText("");
             sugprod.setText("");
             sugprice.setText("");
             google.setSelected(false);
             alexa.setSelected(false);
            /* String image=jTextField1.getText();
             image = image.replace("\\","\\\\");
                     
             
          //   pst.setString(1, name.getText());*/
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
        }
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alexaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alexaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Verification().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        jLabel9.setText("");
    }//GEN-LAST:event_nameKeyPressed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        // TODO add your handling code here:
        jLabel10.setText("");
    }//GEN-LAST:event_priceKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alexa;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField category;
    private javax.swing.JCheckBox google;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> room;
    private javax.swing.JTextField sugprice;
    private javax.swing.JTextField sugprod;
    // End of variables declaration//GEN-END:variables
}
