/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shayantan_tech;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaya
 */
public class Build extends javax.swing.JFrame {
    PreparedStatement stat1,stat2,stat3,stat4,stat5,stat6,stat7;
    Connection con = null;
    ResultSet rs, rs1,rs2,rs3,rs4,rs5,rs6,rs7;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";

    /**
     * Creates new form Build
     */
    public Build(String name,String assist) {
        initComponents();
       // String user=name;
        username.setText(name);
        ass.setText(assist);
        show_products();
        show_price();
        show_sug();
        
    }
    public ArrayList<User1> userList(){
        ArrayList<User1> usersList = new ArrayList<>();
        String uname = username.getText();
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          //  String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
            con = DriverManager.getConnection(url);
            stat4=con.prepareStatement("Select prodname,price,brand from users where name=?");
            stat4.setString(1,uname);
            rs4=stat4.executeQuery();
            User1 user;
            while(rs4.next()){
                user=new User1(rs4.getString("prodname"),rs4.getInt("price"),rs4.getString("brand"));
                usersList.add(user);
            }
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
        return usersList;
        
    }
    public void show_products(){
        ArrayList<User1> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable_display_user.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getProdname();
            row[1]=list.get(i).getPrice();
            row[2]=list.get(i).getBrand();
            model.addRow(row);
        }
    }
    public void show_price(){
        String uname = username.getText();
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          //  String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
            con = DriverManager.getConnection(url);
            stat3=con.prepareStatement("Select sum(price) as sum from users where name=?");
            stat3.setString(1,uname);
            rs3=stat3.executeQuery();
            while(rs3.next())
            {
            price.setText((String) rs3.getString("sum"));
            }
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
        
    }
    public void show_sug()
    {
        String u=username.getText();
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          //  String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
            con = DriverManager.getConnection(url);
            stat2=con.prepareStatement("Select distinct sugprod from product2 inner join users on product2.name = users.prodname AND users.Name=? AND product2.sugprod IS NOT NULL");
            stat2.setString(1,u);
            rs2=stat2.executeQuery();
            while(rs2.next())
            {
               Suglist.addItem(rs2.getString("sugprod"));
            }
            
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
    }

    private Build() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_user = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Suglist = new javax.swing.JComboBox<>();
        sugprice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        ass = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Cost and suggestions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1032, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 29)); // NOI18N
        jLabel2.setText("Thank you ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 109, -1, 66));

        username.setFont(new java.awt.Font("Times New Roman", 0, 29)); // NOI18N
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 109, 311, 66));

        jTable_display_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Brand"
            }
        ));
        jScrollPane1.setViewportView(jTable_display_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 185, 1002, 155));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel3.setText("Total Price:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 356, 144, 38));

        price.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 356, 158, 38));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel4.setText("Suggestions based on avobe products:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 340, 51));

        Suglist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuglistActionPerformed(evt);
            }
        });
        getContentPane().add(Suglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 208, 51));

        sugprice.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        getContentPane().add(sugprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 160, 51));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel5.setText("Price:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 190, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/iconfinder_list-add_118777.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 550, 160, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shaya\\Downloads\\iconfinder_view-refresh_118801.png")); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 356, -1, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/iconfinder_Arrow_Left_1063872.png"))); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 146, -1));
        getContentPane().add(ass, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 109, 45, 27));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\shaya\\Downloads\\iconfinder_f-cross_256_282471.png")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 356, 103, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/brick-wall-painted-white_1194-7526.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 320));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/brick-wall-painted-white_1194-7526.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 400, 320));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shayantan_tech/frame2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 660, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SuglistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuglistActionPerformed
        // TODO add your handling code here:
        String r=(String) Suglist.getSelectedItem();
        try
        {
//            String r = (String) roombox.getSelectedItem();
//            System.out.println(r);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            stat1=con.prepareStatement("select sugprodprice from product2 where sugprod=?");
            stat1.setString(1,r);
            rs1=stat1.executeQuery();
            while(rs1.next())
            {
                sugprice.setText((String)rs1.getString("sugprodprice"));
            }
            con = DriverManager.getConnection(url);
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
        
        
    }//GEN-LAST:event_SuglistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String xyz=(String)Suglist.getSelectedItem();
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
             con = DriverManager.getConnection(url);
             stat6=con.prepareStatement("insert into users(name,prodname,price)values(?,?,?)");
             stat6.setString(1, username.getText());
             stat6.setString(2,xyz);
            // System.out.println(user.getText());
             stat6.setString(3,sugprice.getText());
            // System.out.println(pr);
             stat6.executeUpdate();
             JOptionPane.showMessageDialog(null,"Success");
            
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
        //catch(exception e)
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name;
        name = username.getText();
        String assistant=ass.getText();
        new Build(name,assistant).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        String name;
        name = username.getText();
        String assistant=ass.getText();
        dispose();
        new Bedroom(assistant,name).setVisible(true);
        
        
    }//GEN-LAST:event_BackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String n=username.getText();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // String url = "jdbc:sqlserver://localhost:1433;databaseName=test;integratedSecurity=true";
             con = DriverManager.getConnection(url);
             stat7=con.prepareStatement("delete from users where Name=?");
             stat7.setString(1,n);
             stat7.execute();
             JOptionPane.showMessageDialog(null,"Deleted");
             
            
        }catch(ClassNotFoundException | SQLException e)
        {
            System.out.println("e");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Build.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Build.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Build.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Build.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Build().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> Suglist;
    private javax.swing.JLabel ass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_user;
    private javax.swing.JLabel price;
    private javax.swing.JLabel sugprice;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
